services:
  - type: web
    name: rpngc-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    healthCheckPath: /admin/login/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONUNBUFFERED
        value: "1"
