# Generated by Django 4.2.7 on 2025-09-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_full_form_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='province_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_profiles', to='recruitment.province'),
        ),
        migrations.AddField(
            model_name='application',
            name='criminal_conviction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='declaration_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='from_bougainville',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='reason_for_applying',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reservist_2021_2022',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='signature_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='years_experience',
            field=models.CharField(blank=True, choices=[('1-2', '1–2'), ('2-5', '2–5'), ('5-7', '5–7'), ('OTHER', 'Other')], max_length=8),
        ),
        migrations.AddField(
            model_name='application',
            name='years_experience_other',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='BackgroundReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position_title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='recruitment.applicantprofile')),
            ],
            options={
                'db_table': 'applicant_background_refs',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['applicant', 'name'], name='applicant_b_applica_a045ac_idx')],
            },
        ),
    ]
