# Generated by Django 4.2.7 on 2025-09-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_applicantprofile_email_and_more'),
        ('recruitment', '0005_create_reference'),
    ]

    operations = [
    ]
