# Generated by Django 4.2.7 on 2025-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_merge_20250925_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BackgroundReference',
        ),
    ]
