# Generated by Django 4.2.7 on 2025-09-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_migrate_education_province_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentcycle',
            name='criteria',
            field=models.TextField(blank=True, help_text='Public recruitment criteria shown to applicants.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCREENING', 'Screening'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
