# Generated by Django 4.2.7 on 2025-09-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_recruitmentcycle_criteria_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentcycle',
            name='criteria',
        ),
    ]
