# Generated by Django 4.2.7 on 2025-10-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_remove_recruitmentcycle_criteria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alternativecontact',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='educationrecord',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='applicant',
        ),
        migrations.AddField(
            model_name='alternativecontact',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_contact', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='application',
            name='rec_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('RESERVE', 'Reservist'), ('SPECIAL', 'Cadet')], db_index=True, default='REGULAR', help_text='Chosen recruitment stream; must match the selected cycle.', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='educationrecord',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='reference',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='recruitment.application'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('application', 'doc_type')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['rec_type'], name='application_rec_typ_08c951_idx'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='applicant',
        ),
    ]
