# Generated by Django 4.2.7 on 2025-10-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_alter_document_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativecontact',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alt_contact', to='recruitment.application'),
        ),
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.application'),
        ),
        migrations.AlterField(
            model_name='educationrecord',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='recruitment.application'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='recruitment.application'),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='recruitment.application'),
        ),
    ]
